### ISSUE TITLE
"auto" inserted instead of line breaks in TOC

### ISSUE THREAD

**Issue by uli-weltersbach** [AlanWalk/markdown-toc#65]
I'm having an issue where each line in the TOC is pre- and suffixed with the text "auto".
It seems like the text "auto" is inserted instead of linebreaks.

```html
<!-- TOC -->autoauto- [1. Terminology](#1-terminology)auto- [2. VCS preparation](#2-vcs-preparation)auto- [3. File preparation](#3-file-preparation)auto    - [3.1. Full & partial package](#31-full--partial-package)auto    - [3.2. Partial package only](#32-partial-package-only)auto    - [3.3. Full & partial package (continued)](#33-full--partial-package-continued)auto- [4. VCS finalization](#4-vcs-finalization)autoauto<!-- /TOC -->
```

I haven't experienced the issue prior to updating VS Code, so it *might* be related to changes in the latest version.
My version:
```
Version: 1.29.0 (user setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by Gliptal** [comment]
Same here, on 1.29.0

**Comment by dansanduleac** [comment]
This was working on 1.28.x, I encountered this as soon as VsCode updated to 1.29.0.

**Comment by widdowquinn** [comment]
Same here, occurred with the update to 1.29.0

**Comment by JasperCodes** [comment]
I have this issue as well since the update to 1.29.0

**Comment by pigreco** [comment]
me too, same problem 1.29.0

**Comment by gfx** [comment]
I guess this is a new breaking feature of 1.29.0:

https://code.visualstudio.com/updates/v1_29#_new-default-for-fileseol-auto

> New default for files.eol: auto
> The files.eol end of line setting now has a new default value auto. When set to auto, the end of line character for new files is specific to the operating system. It is \r\n on Windows and \n on macOS and Linux. You can also still explicitly set file.eol to \n or \r\n.

**Comment by neerolyte** [comment]
Setting eol back to `\n` is an adequate work around for me:

![image](https://user-images.githubusercontent.com/1070702/48453225-90b48e80-e806-11e8-8941-002b8c376c72.png)

**Comment by DaveMcBrave** [comment]
> Setting eol back to `\n` is an adequate work around for me:
> 
> ![image](https://user-images.githubusercontent.com/1070702/48453225-90b48e80-e806-11e8-8941-002b8c376c72.png)

This works for me, thanks!

**Comment by imwyw** [comment]
> Setting eol back to `\n` is an adequate work around for me:
> 
> ![image](https://user-images.githubusercontent.com/1070702/48453225-90b48e80-e806-11e8-8941-002b8c376c72.png)

it's work,thanks

**Comment by rajinder-yadav** [comment]
v1.5.6 I have been seeing this issues for a while now, TOC is not getting generated correctly.

![screenshot_20181118_184656](https://user-images.githubusercontent.com/439226/48679830-c341ec80-eb62-11e8-89fd-516ac5386836.png)

**Comment by rajinder-yadav** [comment]
I do have a workaround just need to use global search-replace like this.

Make sure to select the ".*" 

![snr](https://user-images.githubusercontent.com/439226/48679906-b1ad1480-eb63-11e8-97fb-6c4f0cb58067.png)

**Comment by zhongxiaolian** [comment]
对对对

**Comment by DonkeyTable** [comment]
Well done lads /n works for me.

Donkey<T>

**Comment by fedulovivan** [comment]
Well, root cause of this issue is now clear, but switching from **auto** to **\n** in global settings is workaround only. Global editor option "auto" should be handled by this plugin.

**Comment by xploreraj** [comment]
Please update the plugin to handle the change. Thanks!

**Comment by zybbigpy** [comment]
enter settings and then set eol as \n and it works!

**Comment by vestayin** [comment]
I experienced the same issue that string "auto" was used as line breaking char. After change settings of files.eof from "auto" (OS native line breaking) to "\n", the problem was resolved. Added comment here because this bug should be fixed soon since this plugin is suggested by VSCode on official site and TOC key feature didn't work at the first time. Not all user understand how to walk around it.

**Comment by realmariano** [comment]
I understand the workaround, my question being, if I change the global setting, will I break something else, eg. will my python programs work properly when importing data for example? There´s no way to set this property only to .md extension?

**Comment by pauby** [comment]
Any traction on getting this fixed or on #72 getting merged?

**Comment by huntertran** [comment]
Is there any update on this bug or the project is abandoned?

**Comment by aydjay** [comment]
STill having this issue using VSCode 1.33.1 and Markdown TOC V1.5.6

**Comment by jamezpolley** [comment]
"Latest commit 1fc815e  on Apr 9, 2018" - I think its safe to regard this as abandoned.

**Comment by pauby** [comment]
I would either contact the owner and take this over or fork it, move the PR's over and work on it but I have no knowledge of how VSCode Extensions work and no time to learn at the moment. BUT if anybody has the knowledge and energy I would gladly help where needed.

**Comment by martijnvanschie** [comment]
Shame this is not being updated. Work around might work but i'm not sure about the impact on other features.
Also microsoft still promotes this extension on their markdown page.
[Markdown and Visual Studio Code](https://code.visualstudio.com/docs/languages/markdown)

**Comment by p-kaczynski** [comment]
This is a very useful extension, but obviously seems abandoned. 

I feel what we should avoid is getting numerous forks with numerous VS Marketplace submissions.

How about forking to a dedicated "GitHub Team for Open Source" organisation and repo, and just keeping a number of maintainers (so that the scenario of the sole maintainer falling off the face of the Earth does not repeat in the future)?

**Comment by aydjay** [comment]
That sound like an ideal solution

**Comment by kenorb** [comment]
Auto setting didn't work on macOS, it generated a mess with `auto` everywhere, not toc. I'm using 1.5.6. Changing to `\n` in the user settings worked.

**Comment by dialex** [comment]
> I feel what we should avoid is getting numerous forks with numerous VS Marketplace submissions.

100% agreed

> How about forking to a dedicated "GitHub Team for Open Source" organisation and repo (...)

I'm curious @p-kaczynski , does such an org already exist?

Wouldn't the same thing happen, like a group of 10 devs but only 1 knows how to maintain extension X? Such org might have to blindly trust the PRs being submitted.

**Comment by dialex** [comment]
Found it! There's an org for it https://github.com/rejuvenate/rejuvenate
Who will ask them to fork this repo?

**Comment by huntertran** [comment]
I managed to fix all the tslints (which is required to build new version) and merge the pull request.
The new version of this extension can be found at [this marketplace link](https://marketplace.visualstudio.com/items?itemName=huntertran.auto-markdown-toc)
[Source code](https://github.com/huntertran/markdown-toc)

If you found any issue related to code refactoring, please create new issue (and pull request if you can fix it). Many thanks

**Comment by hackjackyer** [comment]
> Setting eol back to `\n` is an adequate work around for me:
> 
> ![image](https://user-images.githubusercontent.com/1070702/48453225-90b48e80-e806-11e8-8941-002b8c376c72.png)

its really highly help for me

**Comment by martijnvanschie** [comment]
Thanks for taking the time to fix this. 
It works again. Also with Eol: Default.

**Comment by kghose** [comment]
I guess this hasn't been fixed in the release on VS Code marketplace? I got this issue in a fresh install.
